# Generated by Django 2.2 on 2020-02-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('grad_year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noble_tutoring.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(to='noble_tutoring.StudentUser')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='courses',
            field=models.ManyToManyField(to='noble_tutoring.Course'),
        ),
    ]
